---
name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Navigating to the project directory
        uses: cd codebase/rdicidr-0.1.0

      - name: Install dependencies
        run: npm install

      - name: Linter (ESLint Fixes)
        run: npm run lint:fix

      - name: Linter (ESLint)
        run: npm run lint

      - name: Formatter (Prettier Write)
        run: npm run prettier:write

      - name: Formatter (Prettier)
        run: npm run prettier

      - name: Test (Jest)
        env:
          CI: true
        run: npm run test

      - name: Build
        run: npm run build
